package allianz.core.identities;

import org.openqa.selenium.By;

import java.util.HashMap;

public class AndroidIdentities {

    private static HashMap<String, By> androidIdentities;

    private AndroidIdentities() {
    }

    public static HashMap<String, By> getAndroidIdentities() {

        if (androidIdentities == null)
            androidIdentities = new HashMap<String, By>();

        if (androidIdentities.size() <= 0)
            initAndroidIdentities();

        return androidIdentities;
    }

    private static void addId(String key, By value) {
        androidIdentities.put(key, value);
    }

    private static void initAndroidIdentities() {

        addId("KARŞILAMA EKRANI GİRİŞ YAP", By.id("com.accenture.oneapp.prep:id/btn_view_main_board_not_login"));
        addId("TC KİMLİK NUMARASI", By.id("com.accenture.oneapp.prep:id/input_edittext"));
        addId("ŞİFRENİZ", By.xpath("//*[@resource-id='com.accenture.oneapp.prep:id/input_password']//android.widget.EditText"));
        addId("GİRİŞ YAP", By.id("com.accenture.oneapp.prep:id/action_signin"));
        addId("UYGULAMAMIZA HOŞ GELDİNİZ DEVAM ET", By.id("com.accenture.oneapp.prep:id/button_continue"));

        //LOGİNSİZ MYALLİANZ
        addId("TANITIM EKRANI KAPAT BUTONU", By.id("com.accenture.oneapp.prep:id/mato_close_button"));
        addId("AMBULANS ÇAĞIR LOGİNSİZ", By.id("com.accenture.oneapp.prep:id/itv_view_main_board_not_login_call_ambulance"));
        //addId("ARAMA YAP LOGİNSİZ", By.id("com.accenture.oneapp.prep:id/action_primary"));
        addId("MÜŞTERİ HİZMETLERİ ARAMA YAP LOGİNSİZ", By.id("com.accenture.oneapp.prep:id/action_primary"));
        addId("ARAMA YAP LOGİNSİZ", By.id("com.accenture.oneapp.prep:id/btn_sheet_item_button"));
        addId("SAĞLIK HATTINI ARA DEVAM", By.id("com.accenture.oneapp.prep:id/action_primary"));
        addId("EKRANDA AMBULANS NUMARASI", By.xpath("//android.widget.EditText[contains(@text,'0216')]"));
        addId("SAĞLIK HATTINI ARA LOGİNSİZ", By.id("com.accenture.oneapp.prep:id/itv_view_main_board_not_login_call_health_line"));
        addId("EKRANDA SAĞLIK HATTI NUMARASI", By.xpath("//android.widget.EditText[contains(@text,'0850')]"));
        addId("DR ALLİANZ LOGİNSİZ", By.id("com.accenture.oneapp.prep:id/itv_view_main_board_not_login_dr_allianz"));
        addId("DR ALLİANZ'I ARA LOGİNSİZ", By.xpath("//android.widget.Button[contains(@text, 'Allianz')]"));
        addId("MÜŞTERİ HİZMETLERİ ", By.xpath("//android.widget.TextView[contains(@text, 'Hizmetleri')]"));
        addId("ÇOCUĞUMUN SAĞLIĞI", By.id("com.accenture.oneapp.prep:id/board_item_child_health"));
        addId("YENİ ÇOCUK EKLE", By.xpath("//android.widget.Button"));
        addId("ÇOCUĞUN ADI", By.xpath("(//android.widget.EditText)[1]"));
        addId("ÇOCUĞUN SOYADI", By.xpath("(//android.widget.EditText)[2]"));
        addId("ÇOCUĞUN DOĞUM TARİHİ", By.xpath("(//android.widget.TextView)[6]"));
        addId("TARİH KAYDET", By.id("android:id/button1"));
        addId("ÇOCUK EKLE", By.id("com.accenture.oneapp.prep:id/add_update_child_button"));
        addId("ANLAŞMALI KURUM BUL LOGİNSİZ", By.id("com.accenture.oneapp.prep:id/itv_view_triple_item_2"));
        addId("SAĞLIK KURUMU BUL LOGİNSİZ", By.xpath("//android.widget.LinearLayout/android.view.ViewGroup[1]\n"));
        addId("SAĞLIK KURUMU BUL FİLTRE UYGULA LOGİNSİZ", By.xpath("//*[@text='Uygula']"));
        addId("HASARIM VAR LOGİNSİZ", By.xpath("//*[@text='Hasarım Var']"));
        addId("HASARIM VAR ALLİANZIM LOGİNSİZ", By.id("com.accenture.oneapp.prep:id/itv_view_triple_item_1"));
        addId("GİRİŞ EKRANI", By.id("android:id/content"));
        addId("MÜŞTERİ HİZMETLERİ LOGİNSİZ", By.id("com.accenture.oneapp.prep:id/itv_view_triple_item_3"));
        addId("SAĞLIKLI CÜZDANIMLA SAĞLIKLI PUANLAR ALLİANZDA POPUP KAPAT", By.id("com.accenture.oneapp.prep:id/mato_close_button"));
        addId("KURUM/DOKTOR BUL", By.id("com.accenture.oneapp.prep:id/institution_doctor_find_edit_text"));
        addId("LİSTEDEKİ İLK HASTANE", By.id("com.accenture.oneapp.prep:id/list_first_textView"));
        //addId("AMERİKAN HASTANESİ ADRES BİLGİSİ", By.xpath("//android.widget.TextView[contains(@text, 'Güzel Bahçe Sokak')]"));
        //addId("AMERİKAN HASTANESİ TELEFON BİLGİSİ", By.xpath("//android.widget.TextView[@text='4443777']"));
        addId("HASTANE ADRES BİLGİSİ", By.id("com.accenture.oneapp.prep:id/institution_detail_address_textView"));
        addId("HASTANE TELEFON BİLGİSİ", By.id("com.accenture.oneapp.prep:id/phone_layout"));
        addId("RANDEVU AL", By.id("com.accenture.oneapp.prep:id/make_appointment_layout"));
        addId("SAĞLIĞIM TABI", By.id("com.accenture.oneapp.prep:id/action_myhealth"));
        addId("AKTİF POLİÇE", By.xpath("//*[@text='Bireysel - Modüler Sağlık Sigortası']"));
        addId("SAĞLIK POLİÇESİ PDF GÖRÜNTÜLE", By.xpath("//android.widget.LinearLayout[2]/android.widget.LinearLayout[2]/android.widget.LinearLayout"));
        addId("GRUP SAĞLIK SİGORTASI", By.xpath("//*[@text='Grup - Grup Sağlık Sigortası']"));
        addId("POLİÇE NO", By.id("com.accenture.oneapp.prep:id/policy_details_number"));
        addId("SAĞLIK HARCAMASI TALEBİ", By.id("com.accenture.oneapp.prep:id/create_health_refund"));
        addId("SAĞLIK KARTINI GÖRÜNTÜLE BUTONU", By.id("com.accenture.oneapp.prep:id/action_show_healthCard"));
        addId("SAĞLIK KARTI NO BAŞLIĞI", By.id("com.accenture.oneapp.prep:id/text_health_card_title"));
        addId("SAĞLIK HARCAMALARIM BUTONU", By.id("com.accenture.oneapp.prep:id/my_health_expenses"));
        addId("SAĞLIK HARCAMALARIM SAĞLIK HARCAMA TALEBİ BUTONU", By.id("com.accenture.oneapp.prep:id/refund_create"));
        addId("SAĞLIK HARCAMALARIM LİSTESİ", By.id("com.accenture.oneapp.prep:id/refund_list"));
        addId("SAĞLIK HARCAMALARIM GERİ DÖN BUTONU", By.xpath("//android.widget.ImageButton[@content-desc='Yukarı git']"));
        addId("SAĞLIK HARCAMASI DETAYI OK BUTONU", By.id("com.accenture.oneapp.prep:id/refund_detail_arrow"));
        addId("SAĞLIK HARCAMA TALEBİ DOSYA NUMARASI", By.id("com.accenture.oneapp.prep:id/refund_details_file_number"));
        addId("BELGELERİ YÜKLE", By.xpath("//*[@text='Belgeleri Yükle']"));
        addId("VAR OLAN FOTOĞRAFI SEÇ", By.xpath("//*[@text='Var Olan Fotoğrafı Seç']"));
        addId("FOTOĞRAF", By.xpath("(//android.widget.ImageView[@resource-id='com.google.android.documentsui:id/icon_thumb'])[2]"));
        addId("FOTOĞRAF TAMAM", By.xpath("//android.widget.TextView[contains(@text,'']"));
        addId("SAĞLIK HARCAMA TALEBİ DEVAM", By.xpath("//*[@text='Devam']"));
        addId("FATURA TARİHİ SAĞLIK", By.id("com.accenture.oneapp.prep:id/health_refund_create_bill_date"));
        addId("FATURA TARİHİ SAĞLIK SEÇİMİ", By.id("android:id/button1"));
        addId("HİZMET TARİHİ SAĞLIK", By.id("com.accenture.oneapp.prep:id/health_refund_loss_date"));
        addId("HİZMET TARİHİ SAĞLIK SEÇİMİ", By.id("android:id/button1"));
        addId("FATURA NUMARASI", By.id("com.accenture.oneapp.prep:id/health_refund_create_bill_number"));
        addId("FATURA TUTARI", By.id("com.accenture.oneapp.prep:id/health_refund_create_bill_amount"));
        addId("DOKTOR MUAYENESİ Mİ", By.xpath("//*[@text='Seçiniz']"));
        addId("DOKTOR MUAYENESİ Mİ HAYIR", By.xpath("//*[@text='Hayır']"));
        addId("HARCAMA TALEBİ BAŞARILI TAMAM", By.xpath("//*[@text='Tamam']"));
        addId("DOSYANIZ AÇILDI", By.xpath("//*[@text='Dosyanız Açıldı']"));
        addId("GEÇMİŞ POLİÇELERİM", By.xpath("//*[@text='Geçmiş Poliçelerim']"));
        addId("GEÇMİŞ SAĞLIK POLİÇESİ", By.xpath("//androidx.recyclerview.widget.RecyclerView/android.view.ViewGroup/android.widget.LinearLayout"));
        addId("POLİÇENİZİN SÜRESİZ DOLMUŞTUR", By.xpath("//*[@text='Poliçenizin süresi dolmuştur']"));
        addId("SAĞLIK CÜZDANIM", By.xpath("//androidx.recyclerview.widget.RecyclerView/android.widget.LinearLayout[3]"));
        addId("SIKÇA SORULAN SORULAR", By.id("com.accenture.oneapp.prep:id/txt_faqs"));
        addId("SIKÇA SORULAN SORULAR METNİ", By.id("com.accenture.oneapp.prep:id/rv_wallet_faqs"));
        addId("ARACI", By.xpath("//*[@text='Aracı']"));
        addId("ARACI NUMARASI", By.xpath("//*[@text='']"));
        addId("TAMAMLAYICI SAĞLIK POLİÇESİ", By.xpath("//*[@text='amamlayıcı Sağlık Poliçesi']"));
        addId("POLİÇENİZE ÖZEL HİZMETLER", By.id("com.accenture.oneapp.prep:id/my_health_ivr"));
        addId("POLİÇENİZE ÖZEL HİZMETLER SAYFASI", By.id("android:id/content"));
        addId("KULLANILABİLİR SAĞLIKLI PUANLARIM", By.id("com.accenture.oneapp.prep:id/card_health_points"));
        addId("ŞİFRESİZ GİRİŞ YAP HAYIR", By.id("com.accenture.oneapp.prep:id/fingerprint_no_button"));
        addId("GİRİŞ SONRASI KABUL EDİYORUM", By.id("com.accenture.oneapp.prep:id/login_permission_dialog_ok_button"));
        addId("KAMPANYALAR", By.id("re.oneapp:id/board_item_campaigns"));
        addId("KAPMANYA YOK", By.xpath("//*[@text='Şuan aktif kampanyanız bulunmamaktadır!']"));
        addId("İLETİŞİM FORMU", By.id("com.accenture.oneapp.prep:id/btn_contact"));
        addId("TERCİH EDİLEN İLETİŞİM KANALI", By.id("com.accenture.oneapp.prep:id/spinner_preferred_contact_line"));
        addId("TERCİH EDİLEN İLETİŞİM KANALI LİSTESİNİN ÜÇÜNCÜ ELEMANI", By.xpath("//android.widget.TextView[3]"));
        addId("İLETİŞİM FORMU KONU", By.id("com.accenture.oneapp.prep:id/spinner_contact_form_type"));
        addId("İLETİŞİM FORMU KONU LİSTESİNİN İLK ELEMANI", By.xpath("//android.widget.TextView[1]"));
        addId("İLETİŞİM FORMU AÇIKLAMA", By.id("com.accenture.oneapp.prep:id/input_explanation"));
        addId("İLETİŞİM FORMU GÖNDER BUTONU", By.xpath("//android.widget.Button"));
        addId("İLETİŞİM FORMU BAŞARILI POP UP", By.id("android:id/content"));
        addId("AYARLAR", By.xpath("//*[@text='Ayarlar']"));
        addId("UYGULAMA DİLİNİ DEĞİŞTİR", By.xpath("//*[@text='Uygulama Dilini Değiştir']"));
        addId("CHANGE APP LANGUAGE", By.xpath("//*[@text='Change App Language']"));
        addId("ENGLISH", By.xpath("//*[@text='English']"));
        addId("TÜRKÇE", By.xpath("//*[@text='Türkçe']"));
        addId("SAĞLIK CÜZDANI KAPAT", By.id("m.accenture.oneapp:id/mato_close_button"));
        addId("KONUM İZİN VER", By.id("com.android.packageinstaller:id/permission_allow_button"));
        addId("SÜZGEÇ", By.id("com.accenture.oneapp.prep:id/mydoc_toolbar_filter_image_view"));
        addId("KURUM TİPİ SEÇİNİZ", By.xpath("//*[@text='Kurum Tipi: Seçiniz']"));
        addId("KURUM TİPİ TIP MERKEZİ", By.xpath("//*[@text='Tıp Merkezi']"));
        addId("KAPSAM SEÇİNİZ", By.xpath("//*[@text='Kapsam: Seçiniz']"));
        addId("KAPSAM TÜM ANLAŞMALI KURUMLAR", By.xpath("//*[@text='Tüm Anlaşmalı Kurumlar']"));
        addId("İL SEÇİNİZ", By.xpath("//*[@text='İl: Seçiniz']"));
        addId("İL ANKARA", By.xpath("//*[@text='ANKARA']"));
        addId("SAĞLIK KURUMU LİSTE", By.id("com.accenture.oneapp.prep:id/tabs_button_right"));
        addId("SAĞLIK KURUMU", By.xpath("//androidx.recyclerview.widget.RecyclerView/android.widget.LinearLayout[1]"));
        addId("SAĞLIK KURUMU TELEFON", By.id("com.accenture.oneapp.prep:id/institution_detail_phone_number_textView"));
        addId("HIZLI İŞLEMLER", By.id("com.accenture.oneapp.prep:id/container_quick_actions"));
        addId("POLİÇE DETAYLARINI GÖSTER", By.xpath("//android.view.ViewGroup/android.widget.FrameLayout/android.view.ViewGroup/android.widget.LinearLayout/android.view.ViewGroup[3]"));
        addId("POLİÇE SAYFASI", By.id("com.accenture.oneapp.prep:id/policy_details_slider"));
        addId("FOTOĞRAF ALANI", By.id("com.accenture.oneapp.prep:id/text_upload_image"));
        addId("FOTOĞRAF KALDIR", By.xpath("//android.widget.FrameLayout/android.widget.ListView/android.widget.TextView[3]"));

        //ARABAM
        addId("ŞİFRE AL YENİLE", By.id("com.accenture.oneapp.prep:id/action_password_operation"));
        addId("CEP TELEFONU NUMARASI", By.xpath("//*[@resource-id='com.accenture.oneapp.prep:id/input_phone']//android.widget.EditText"));
        addId("GÖNDER", By.xpath("//*[@text='Gönder']"));
        addId("ARABAM TABI", By.xpath("//*[@text='Arabam']"));
        addId("AKTİF ARAÇ POLİÇESİ", By.id("om.accenture.oneapp:id/text_policy_name"));
        addId("GÜNCEL ARAÇ POLİÇELERİ EN ÜSTTEKİ POLİÇE", By.xpath("(//android.view.View[@resource-id=\"com.accenture.oneapp.prep:id/view_container_policy\"])[1]"));
        addId("TRAFİK POLİÇESİ DETAYLARI GÖSTER", By.id("com.accenture.oneapp.prep:id/show_hide_detail_text"));
        addId("TRAFİK POLİÇESİ DETAYLARI GİZLE", By.id("com.accenture.oneapp.prep:id/show_hide_detail_text"));
        addId("HASARLARIM", By.xpath("//*[@text='Hasarlarım']"));
        addId("AÇIK HASAR YOK UYARISI", By.id("com.accenture.oneapp.prep:id/empty_list_title"));
        addId("HASARIM VAR", By.xpath("//*[@text='Hasarım Var']"));
        addId("HASARIM VAR ALLİANZIM", By.id("com.accenture.oneapp.prep:id/itv_view_triple_item_1"));
        addId("HASARIM VAR SAYFASI", By.id("android:id/content"));
        addId("EN ÜSTTEKİ ARAÇ", By.xpath("//android.view.View[2]/android.view.View/android.view.View[5]"));
        addId("ÇEKİCİ ÇAĞIR", By.xpath("//android.widget.Button[@text='Çekici Çağır']"));
        addId("SERVİS SEÇ", By.xpath("//android.widget.Button[@text='Servis Seç']"));
        addId("KONUMU KULLAN İNAKTİF", By.xpath("//android.view.View[4]/android.view.View[2]/android.widget.CheckBox"));
        addId("BİR YER ARA", By.xpath("//*[@text='Bir Yer Ara']"));
        addId("ARAMA ÇUBUĞU", By.xpath("//android.view.View[2]/android.view.View[2]/android.view.View/android.widget.EditText"));
        addId("SERVİS ARAMA SONUCU İLK SIRA", By.xpath("//android.app.Dialog/android.view.View/android.view.View[4]/android.view.View[1]/android.widget.Image[@text='rightArrowBlue']"));
        addId("SERVİS KONUM ARAMA SONUCU", By.xpath("//android.widget.TextView[contains(@text, 'Türkiye')]"));
        addId("DİĞER SERVİSLERDEN EN YAKIN", By.xpath("//android.view.View[@text='En Yakın']"));
        addId("SERVİS BİLGİLERİ", By.xpath("//android.view.View[@text='Servis Bilgileri']"));
        addId("ÇEKİCİ TALEBİNİZ ALINDI", By.xpath("//android.view.View[@text='Çekici talebiniz alındı.']"));
        addId("ADRES YAZ", By.xpath("//android.widget.Button[@text='Adres Yaz']"));
        addId("ÇEKİCİ İL SEÇ", By.xpath("//android.view.View[@text='İl Seçin']"));
        addId("ÇEKİCİ İL TAMAM", By.xpath("//*[@text='TAMAM']"));
        addId("ÇEKİCİ İLÇE SEÇ", By.xpath("//android.view.View[@text='İlçe Seçin']"));
        addId("ÇEKİCİ İLÇE TAMAM", By.xpath("//*[@text='TAMAM']"));
        addId("ADRES DETAYI", By.xpath("//android.view.View[4]/android.view.View[2]/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.EditText"));
        addId("ADRES KAYDET", By.xpath("//*[@text='Adresi Kaydet']"));
        addId("ONARIM İÇİN SERVİS BUL", By.xpath("//android.widget.Button[@text='Onarım İçin Servis Bul']"));
        addId("DİĞER SERVİSLERDEN EN ÜSTTEKİ", By.xpath("//android.view.View[@text='En Yakın']"));
        addId("HASAR İHBARI YAPACAĞIM", By.xpath("//android.widget.TextView[@text='Hasar ihbarı yapacağım.']"));
        addId("PARK HALİNDE", By.xpath("//android.widget.Button[@text='Park Halinde']"));
        addId("TAMİR EDİLECEK", By.xpath("//android.widget.Button[@text='Tamir Edilecek']"));
        addId("RUHSAT FOTOĞRAFI EKLEME", By.xpath("//android.widget.Image[@text='add']"));
        addId("RUHSAT FOTOĞRAFI EKLEME DEVAM", By.id("com.accenture.oneapp.prep:id/btnTakePicUpload"));
        addId("İZİN VER", By.id("com.android.packageinstaller:id/permission_allow_button"));
        addId("GALERİ FOTOĞRAFI", By.xpath("(//android.widget.ImageView[@resource-id='com.accenture.oneapp.prep:id/iv_image'])[2]"));
        //addId("GALERİ FOTOĞRAFI", By.xpath("(//android.widget.ImageView[@resource-id='com.google.android.documentsui:id/icon_thumb'])[2]"));
        addId("DEVAM ET", By.xpath("//android.widget.Button[@text='Devam Et']"));
        addId("HASAR TARİHİ", By.xpath("//android.view.View[@text='Tarih seçin']"));
        addId("TAKVİMDEN HASAR TARİHİ SEÇİMİ", By.xpath("(//android.view.View[@text='Mayıs 2021']/following-sibling::android.widget.Button[1])"));
        addId("HASAR TARİHİ SEÇ", By.xpath("//android.widget.Button[@text='SEÇ']"));
        addId("ŞU ANKİ KONUMU KULLAN", By.xpath("//android.view.View[@text='Şu anki konumumu kullan']"));
        addId("HASAR YERİ", By.xpath("//android.view.View[2]/android.view.View/android.view.View[3]/android.view.View[2]/android.view.View[2]"));
        addId("HASAR FOTOĞRAFI EKLEME", By.xpath("//android.widget.Image[@text='add']"));
        addId("TAMİR EDİLDİ", By.xpath("//android.widget.Button[@text='Tamir Edildi']"));
        addId("KDV DAHİL TOPLAM TUTAR", By.xpath("//android.view.View[@text='KDV Dahil Toplam Tutar']/following-sibling::android.view.View/android.view.View/android.widget.EditText"));
        addId("TAMİRHANE TCKN", By.xpath("//android.view.View[@text='Tamirhane VKN/TCKN']/following-sibling::android.view.View/android.view.View/android.widget.EditText"));
        addId("IBAN", By.xpath("//android.widget.TextView[@text='IBAN']/following-sibling::android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.widget.EditText"));
        addId("FATURA FOTOĞRAFI EKLEME", By.xpath("//android.widget.Image[@text='add']"));
        addId("BAŞKA BİR ARAÇLA", By.xpath("//android.widget.Button[@text='Başka Bir Araçla']"));
        addId("SADECE KENDİ ARACIM", By.xpath("//android.widget.Button[@text='Sadece Kendi Aracım']"));
        addId("DAHA FAZLA HASAR ÇEŞİDİ", By.xpath("//android.widget.Button[@text='Daha Fazla Hasar Çeşidi']"));
        addId("LASTİK HASARLARI", By.xpath("//android.widget.Button[@text='Lastik Hasarları']"));
        addId("ANAHTAR KAYBI HASARI", By.xpath("//android.widget.Button[@text='Anahtar Kaybı / Hasarı']"));
        addId("SEYİR HALİNDE HASAR", By.xpath("//android.widget.Button[@text='Seyir Halinde Hasar']"));
        addId("DİĞER HIRSIZLIK - HIRSIZLIĞA BAĞLI HASARLAR", By.xpath("//android.widget.Button[@text='Diğer Hırsızlık Hırsızlığa Bağlı Hasarlar']"));
        addId("ŞİDDET İÇERİKLİ HASARLAR / TERÖR FAALİYETLERİ", By.xpath("//android.widget.Button[@text='Şiddet İçerikli Hasarlar/Terör Faaliyetleri']"));
        addId("DOLU", By.xpath("//android.widget.Button[@text='Dolu']"));
        addId("SEL/SU", By.xpath("//android.widget.Button[@text='Sel / Su']"));
        addId("DİĞER HAVA ŞARTLARI", By.xpath("//android.widget.Button[@text='Diğer Hava Şartları']"));
        addId("YABANİ HAYVANLAR", By.xpath("//android.widget.Button[@text='Yabani Hayvanlar']"));
        addId("DİĞER HASARLAR", By.xpath("//android.widget.Button[@text='Diğer Hasarlar']"));
        addId("CAM KIRILMASI", By.xpath("//android.widget.Button[@text='Cam Kırılması']"));
        addId("HASAR İHBARINA DEVAM ET", By.xpath("//android.widget.Button[@text='Hasar İhbarına Devam Et']"));
        addId("ARAÇ ÇALINMA", By.xpath("//android.widget.Button[@text='Araç Çalınma']"));
        addId("KARAKOL TUTANAĞI EKLE", By.xpath("//*[@text='add']"));
        addId("ANLADIM", By.xpath("//*[@text='Anladım']"));
        addId("GEÇMİŞ TRAFİK POLİÇESİ", By.xpath("//*[@text='Trafik']"));
        addId("GEÇMİŞ TRAFİK POLİÇESİ DETAYLARI GÖSTER", By.xpath("//*[@text='Detayları Göster']"));
        addId("KAZA TESPİT TUTANAĞI DOLDUR", By.xpath("//*[@text='Kaza tespit tutanağı doldur.']"));
        addId("KAZA TESPİT TUTANAĞI REHBERİ", By.xpath("//*[@text='Kaza Tespit Tutanağı Rehberi']"));
        addId("KAZA TESPİT TUTANAĞI GÖRÜNTÜLE", By.xpath("//android.widget.Image[@text='policy']"));
        addId("KAZA TESPİT TUTANAĞI", By.xpath("//*[@text='']"));
        addId("MOBİL KAZA TESPİT TUTANAĞI İNDİR", By.xpath("//*[@text='Mobil Kaza Tespit Tutanağı İndir']"));
        addId("GOOGLE PLAY UYGULAMASI", By.xpath("//*[@text='']"));
        addId("HASAR DOSYASI OLUŞTURMA", By.xpath("//*[@text='']"));
        addId("KAZANÇLI SERVİSLERDEN EN ÜSTTEKİ", By.xpath("//*[@text='']"));
        addId("ÖDEME YAP", By.xpath("//*[@text='Ödeme Yap']"));
        addId("ÖDENMEMİŞ TAKSİT SEÇ", By.xpath("(//android.widget.CheckBox[@resource-id=\"com.accenture.oneapp.prep:id/checkbox_contribution_period\"])[1]"));
        addId("GALERİ FOTOĞRAFI TAMAM", By.xpath("//*[@text='Tamam']"));
        addId("HASAR İHBARINIZ ALINDI ONAYI", By.xpath("//android.view.View[@text='Hasar ihbarınız alındı.']"));
        addId("DİĞER TABI", By.xpath("//*[@text='Diğer']"));
        addId("KONUT POLİÇESİ", By.xpath("//*[@text='Konut']"));
        addId("DASK POLİÇESİ", By.xpath("//*[@text='DASK']"));
        addId("GEÇMİŞ POLİÇELERİM SAYFASI", By.id("com.accenture.oneapp.prep:id/decor_content_parent"));
        addId("POLİÇEYİ PDF OLARAK GÖRÜNTÜLE", By.id("com.accenture.oneapp.prep:id/view_policy_pdf"));
        addId("POLİÇE İÇERİĞİ", By.id("com.google.android.apps.docs:id/action_find"));
        addId("MAKBUZU GÖRÜNTÜLE", By.id("com.accenture.oneapp.prep:id/show_receipt"));
        addId("ÖDENMİŞ MAKBUZU GÖRÜNTÜLE", By.xpath("(//android.view.ViewGroup[@resource-id='com.accenture.oneapp.prep:id/paid_maturity_view'])[1]"));
        addId("MAKBUZU GÖRÜNTÜLE SAYFASI", By.id("com.accenture.oneapp.prep:id/stateful_view"));
        addId("KONUT POLİÇESİ ÖDEME YAP", By.id("com.accenture.oneapp.prep:id/text_payment"));
        addId("ÖDENMEMİŞ TAKSİT", By.id("com.accenture.oneapp.prep:id/checkbox_contribution_period"));
        addId("KREDİ KARTI İLE ÖDE", By.id("com.accenture.oneapp.prep:id/action_pay_with_credit_card"));
        addId("KART SAHİBİNİN ADI - SOYADI", By.xpath("(//android.widget.EditText[@resource-id='com.accenture.oneapp.prep:id/input_text'])[1]"));
        addId("KREDİ KARTI NUMARASI", By.xpath("(//android.widget.EditText[@resource-id='com.accenture.oneapp.prep:id/input_text'])[2]"));
        addId("GEÇERLİLİK TARİHİ AY", By.xpath("//*[@text='Ay']"));
        addId("GEÇERLİLİK TARİHİ YIL", By.xpath("//*[@text='Yıl']"));
        addId("GEÇERLİLİK TARİHİ TAMAM", By.xpath("//*[@text='Tamam']"));
        addId("GÜVENLİK KODU", By.xpath("(//android.widget.EditText[@resource-id='com.accenture.oneapp.prep:id/input_text'])[1]"));
        addId("ÖDEME YAP", By.xpath("//*[@text='Ödeme Yap']"));
        addId("GEÇMİŞ POLİÇELERİM", By.xpath("//*[@text='Geçmiş Poliçelerim']"));
        addId("EN ÜSTTEKİ GEÇMİŞ POLİÇE", By.xpath("//*[@text='Konut']"));
        addId("POLİÇENİZİN SÜRESİ DOLMUŞTUR", By.xpath("//*[@text='Poliçenizin süresi dolmuştur']"));
        addId("HASAR DOSYASI OLUŞTURMA", By.xpath("//*[@text='Hasar Dosyası Oluşturma']"));
        addId("DAHİLİ SU", By.xpath("//*[@text='icon_water_damage_default']"));
        addId("KAZA DETAY", By.xpath("//android.widget.EditText[@resource-id='eventDescription']"));
        addId("İLERİ", By.xpath("//*[@text='İleri']"));
        addId("TAKVİM", By.xpath("//android.view.View[@text='Hasar Tarihi']/following-sibling::android.view.View"));
        addId("TARİH", By.xpath("//android.view.View[@text='1']"));
        addId("AYARLA", By.id("android:id/button1"));
        addId("ONARIM TAMAMLANDI MI EVET", By.xpath("//*[@text='icon_yes_default_tr']"));
        addId("TAHMİNİ HASAR TUTARI", By.xpath("//*[@text='Seçiniz']"));
        addId("0-2000 TL", By.xpath("//*[@text='0-2.000 TL']"));
        addId("İLETİŞİM BİLGİLERİ", By.xpath("//*[@text='']"));
        addId("YÜKLEMEK İÇİN TIKLAYIN", By.xpath("//android.widget.Image[@text='icon_upload']"));
        addId("GALERİ FOTOĞRAFI YÜKLE TAMAM", By.xpath("//android.widget.TextView[@resource-id='com.accenture.oneapp.prep:id/menu_crop']"));
        addId("ONAYLA", By.xpath("//android.widget.Button[@text='Onayla']"));
        addId("DEĞERLENDİRME ONAYLA", By.xpath("//android.view.View[@text='ONAYLA']"));
        addId("HASAR DOSYANIZ AÇILMIŞTIR", By.xpath("//*[@text='Hasar Dosyanız Açılmıştır']"));
        addId("DOSYA NUMARASI", By.xpath("//*[@text='Dosya Numaranız:']"));
        addId("HASAR İHBARI SERVİS SEÇ", By.xpath("//android.widget.TextView[@text='Servis Seç']"));
        addId("FATURA TARİHİ", By.xpath("//android.widget.Image[@text='rightArrow']"));
        addId("HASAR İHBARI YAP", By.xpath("//android.widget.Button[@text='Hasar İhbarı Yap']"));

        //MY ALLİANZ
        addId("KONUM İZİN VER", By.id("com.android.packageinstaller:id/permission_allow_button"));
        addId("SÜZGEÇ", By.id("com.accenture.oneapp.prep:id/mydoc_toolbar_filter_image_view"));
        addId("KURUM TİPİ SEÇİNİZ", By.xpath("//*[@text='Kurum Tipi: Seçiniz']"));
        addId("KURUM TİPİ TIP MERKEZİ", By.xpath("//*[@text='Tıp Merkezi']"));
        addId("KAPSAM SEÇİNİZ", By.xpath("//*[@text='Kapsam: Seçiniz']"));
        addId("KAPSAM TÜM ANLAŞMALI KURUMLAR", By.xpath("//*[@text='Tüm Anlaşmalı Kurumlar']"));
        addId("İL SEÇİNİZ", By.xpath("//*[@text='İl: Seçiniz']"));
        addId("İL ANKARA", By.xpath("//*[@text='ANKARA']"));
        addId("HARİTA ÜZERİNDE HASTANE", By.xpath("//android.view.View[@content-desc=\"Özel Dünya Göz Tıp Merkezi Sincan. Maraşal Çakmak MAH. 24. Sokak NO:23 Sincan 06936 Ankara TÜRKİYE.\"]"));
        addId("HARİTA ÜZERİNDE HASTANE ADRESİ", By.id("com.accenture.oneapp.prep:id/map_info_address_text"));
        addId("SAĞLIK KURUMU BUL FİLTRE UYGULA", By.xpath("//*[@text='Uygula']"));
        addId("AKTİF POLİÇE", By.id("com.accenture.oneapp.prep:id/view_container_policy"));
        addId("KALAN LİMİT BİLGİSİ", By.xpath("//android.widget.LinearLayout/android.widget.LinearLayout[2]/android.widget.LinearLayout[4]/android.widget.LinearLayout"));
        addId("KALAN LİMİT BİLGİSİ SAYFASI", By.id("com.accenture.oneapp.prep:id/slider_content_pager"));
        addId("PDF GÖRÜNTÜLE", By.xpath("//android.view.TestView(contains(@text,'Poliçeyi PDF olarak görüntüle' "));
        addId("AMBULANSI ARA", By.id("com.accenture.oneapp.prep:id/btn_call_ambulance"));
        addId("DR ALLİANZ", By.id("com.accenture.oneapp.prep:id/btn_dr_allianz"));
        addId("DR ALLİANZ'I ARA", By.id("com.accenture.oneapp.prep:id/btn_sheet_item_button"));
        addId("HASARIM VAR MYALLİANZ", By.id("com.accenture.oneapp.prep:id/board_item_damaged_assert"));
        addId("MÜŞTERİ HİZMETLERİ ARAMA YAP", By.id("com.accenture.oneapp.prep:id/action_primary"));
        addId("ARAMA YAP", By.id("com.accenture.oneapp.prep:id/btn_sheet_item_button"));
        addId("SAĞLIK HATTINI ARA", By.id("com.accenture.oneapp.prep:id/btn_call_health_line"));
        addId("MÜŞTERİ HİZMETLERİ", By.id("com.accenture.oneapp.prep:id/board_item_call_hot_line"));
        addId("ANLAŞMALI KURUM BUL", By.id("com.accenture.oneapp.prep:id/board_item_find_institution"));
        addId("SAĞLIK KURUMU BUL", By.xpath("//android.widget.LinearLayout/android.view.ViewGroup[1]/android.widget.TextView"));
        addId("GÖRÜNTÜLÜ GÖRÜŞME BAŞLAT", By.xpath("//android.widget.FrameLayout/android.view.ViewGroup/android.widget.LinearLayout/android.widget.Button[2]"));
        addId("KAMPANYALAR", By.id("com.accenture.oneapp.prep:id/board_item_campaigns"));
        addId("HABERLER", By.id("com.accenture.oneapp.prep:id/btn_news"));
        addId("HABERLER BAŞLIĞI", By.id("com.accenture.oneapp.prep:id/action_bar"));
        addId("İLETİŞİM FORMU", By.id("com.accenture.oneapp.prep:id/btn_contact"));
        addId("TERCİH EDİLEN İLETİŞİM KANALI", By.id("com.accenture.oneapp.prep:id/spinner_preferred_contact_line"));
        addId("TERCİH EDİLEN İLETİŞİM KANALI LİSTESİNİN ÜÇÜNCÜ ELEMANI", By.xpath("//android.widget.TextView[3]"));
        addId("İLETİŞİM FORMU KONU", By.id("com.accenture.oneapp.prep:id/spinner_contact_form_type"));
        addId("İLETİŞİM FORMU KONU LİSTESİNİN İLK ELEMANI", By.xpath("//android.widget.TextView[1]"));
        addId("İLETİŞİM FORMU AÇIKLAMA", By.id("com.accenture.oneapp.prep:id/input_explanation"));
        addId("İLETİŞİM FORMU GÖNDER BUTONU", By.xpath("//android.widget.Button"));
        addId("İLETİŞİM FORMU BAŞARILI POP UP", By.id("android:id/content"));
        addId("AYARLAR", By.id("com.accenture.oneapp.prep:id/btn_setting"));
        addId("UYGULAMA DİLİNİ DEĞİŞTİR", By.id("com.accenture.oneapp.prep:id/action_change_app_language"));
        addId("ENGLISH", By.xpath("//*[@text='English']"));
        addId("ÇIKIŞ YAP", By.id("com.accenture.oneapp.prep:id/action_logout"));
        addId("ŞİFRE DEĞİŞTİR", By.id("com.accenture.oneapp.prep:id/action_change_password"));
        addId("ESKİ ŞİFRE", By.xpath("//android.widget.FrameLayout[1]/android.widget.FrameLayout/android.widget.EditText"));
        //addId("ŞİFRENİZ", By.xpath("//android.widget.FrameLayout[2]/android.widget.FrameLayout/android.widget.EditText"));
        addId("ŞİFRENİZİ TEKRARLAYIN", By.xpath("//android.widget.FrameLayout[3]/android.widget.FrameLayout/android.widget.EditText"));
        addId("ŞİFRE DEĞİŞTİR BAŞARILI POP UP", By.id("com.accenture.oneapp.prep:id/dialog_title"));
        addId("ŞİFRE DEĞİŞTİR TAMAM", By.id("com.accenture.oneapp.prep:id/action_primary"));
        addId("ŞİFRE DEĞİŞTİR DEVAM", By.id("com.accenture.oneapp.prep:id/action_continue"));
        //addId("HASARIM VAR", By.id("com.accenture.oneapp.prep:id/board_item_damaged_assert"));
        addId("HASARIM VAR SAYFASI", By.id("android:id/content"));
        addId("KİŞİ İKONU", By.id("com.accenture.oneapp.prep:id/image_logged_icon"));
        addId("VAR OLAN FOTOĞRAFI SEÇ", By.xpath("//android.widget.ListView/android.widget.TextView[1]"));
        addId("GALERİ FOTOĞRAF", By.id("com.android.documentsui:id/icon_thumb"));
        addId("GALERİ TAMAM", By.id("com.accenture.oneapp.prep:id/menu_crop"));
        addId("KAMPANYALAR", By.id("com.accenture.oneapp.prep:id/board_item_campaigns"));
        addId("KAMPANYALAR BAŞLIĞI", By.id("com.accenture.oneapp.prep:id/txt_stories_rv_title"));
        addId("KAMPANYALAR SAYFASI", By.id("com.accenture.oneapp.prep:id/action_bar"));
        addId("TÜM KAMPANYALAR", By.id("com.accenture.oneapp.prep:id/txt_see_all"));
        addId("GECİKMİŞ ÖDEMELER", By.id("com.accenture.oneapp.prep:id/board_item_belated_payment"));
        addId("GECİKMİŞ ÖDEMELER SAYFASI", By.id("android:id/content"));

        //BİRİKİMLERİM TABI
        addId("BİRİKİMLERİM TABI", By.id("com.accenture.oneapp.prep:id/action_mysaving"));
        addId("ALLİANZ YAŞAM EMEKLİLİK İLK POLİÇE/SÖZLEŞMEYE", By.id("com.accenture.oneapp.prep:id/view_container_policy"));
        addId("ALLİANZ YAŞAM EMEKLİLİK POLİÇE/SÖZLEŞMELER SAYFASI", By.id("com.accenture.oneapp.prep:id/contract_details_slider"));
        addId("ALLİANZ YAŞAM EMEKLİLİK KATKI PAYI TUTARI KALEM İKONU", By.id("com.accenture.oneapp.prep:id/details_item_details"));
        addId("ALLİANZ YAŞAM EMEKLİLİK KATKI PAYI TUTARI", By.id("com.accenture.oneapp.prep:id/details_item_text_right"));
        addId("ALLİANZ YAŞAM EMEKLİLİK KATKI PAYI TUTARI GÜNCELLE BUTONU", By.id("com.accenture.oneapp.prep:id/contribution_update_button"));
        addId("ALLİANZ YAŞAM EMEKLİLİK KATKI PAYI TUTARI GÖNDER BUTONU", By.id("com.accenture.oneapp.prep:id/fund_pay_send_info_button"));
        addId("ALLİANZ YAŞAM EMEKLİLİK KATKI PAYI ŞİFRE", By.id("com.accenture.oneapp.prep:id/dialog_sms_code"));
        addId("ALLİANZ YAŞAM EMEKLİLİK KATKI PAYI TUTARI TAMAM BUTONU", By.id("com.accenture.oneapp.prep:id/dialog_sms_send"));
        addId("ALLİANZ YAŞAM EMEKLİLİK ÖDEME PERİYODU VE GÜNÜ KALEM İKONU", By.xpath("//android.widget.FrameLayout/android.widget.ImageView"));
        addId("ALLİANZ YAŞAM EMEKLİLİK ÖDEME PERİYODU VE GÜNÜ ALANI", By.id("com.accenture.oneapp.prep:id/period_day_selection_text"));
        addId("ALLİANZ YAŞAM EMEKLİLİK ÖDEME PERİYODU VE GÜNÜ SÜREÇ", By.xpath("android.widget.NumberPicker[1]/android.widget.Button[2]"));
        //addId("ALLİANZ YAŞAM EMEKLİLİK ÖDEME PERİYODU VE GÜNÜ TAMAM BUTONU", By.id("com.accenture.oneapp.prep:id/dialog_period_day_picker_ok"));
        addId("ALLİANZ YAŞAM EMEKLİLİK ÖDEME PERİYODU VE GÜNÜ GÜNCELLE", By.id("com.accenture.oneapp.prep:id/update_payment_period_save"));
        addId("ALLİANZ YAŞAM EMEKLİLİK ÖDEME PERİYODU VE GÜNÜ GÖNDER BUTONU", By.id("com.accenture.oneapp.prep:id/fund_pay_send_info_button"));
        addId("ALLİANZ YAŞAM EMEKLİLİK ÖDEME PERİYODU VE GÜNÜ ŞİFRE", By.id("com.accenture.oneapp.prep:id/dialog_sms_code"));
        //addId("ALLİANZ YAŞAM EMEKLİLİK ÖDEME PERİYODU VE GÜNÜ TAMAM BUTONU", By.id("com.accenture.oneapp.prep:id/dialog_sms_send"));
        addId("ALLİANZ YAŞAM EMEKLİLİK BİRİKİM DETAYIM TABI", By.id("com.accenture.oneapp.prep:id/contract_details_saving_details"));
        addId("ALLİANZ YAŞAM EMEKLİLİK BİRİKİM DETAYIM SAYFASI", By.id("com.accenture.oneapp.prep:id/saving_details_slider"));
        addId("ALLİANZ YAŞAM EMEKLİLİK ÖDEMELERİM TABI", By.id("com.accenture.oneapp.prep:id/contract_details_payments"));
        addId("ALLİANZ YAŞAM EMEKLİLİK ÖDEMELERİM SAYFASI", By.id("android:id/content"));
        addId("ALLİANZ YAŞAM EMEKLİLİK FONLARIM", By.id("com.accenture.oneapp.prep:id/contract_details_funds"));
        addId("ALLİANZ YAŞAM EMEKLİLİK FONLARIM SAYFASI", By.id("com.accenture.oneapp.prep:id/fund_details_slider"));
        addId("ALLİANZ YAŞAM EMEKLİLİK FON DAĞILIMINDAN ÇIKIŞ ONAY", By.id("com.accenture.oneapp.prep:id/action_primary"));
        addId("ALLİANZ YAŞAM EMEKLİLİK FON PAKETLERİNİ İNCELE BUTONU", By.id("com.accenture.oneapp.prep:id/review_confirmation_dialog_button"));
        addId("ALLİANZ YAŞAM EMEKLİLİK BU PAKETLE DEVAM ET", By.id("com.accenture.oneapp.prep:id/continue_this_fund_package_button"));
        addId("ALLİANZ YAŞAM EMEKLİLİK BİST TEMETTÜ ENDEKSİ EMEKLİLİK YATIRIM FONU", By.xpath("//android.widget.LinearLayout[1]/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.EditText"));
        addId("ALLİANZ YAŞAM EMEKLİLİK KARMA EMEKLİLİK YATIRIM FONU", By.xpath("//android.widget.LinearLayout[2]/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.EditText"));
        addId("ALLİANZ YAŞAM EMEKLİLİK DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU", By.xpath("//android.widget.LinearLayout[3]/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.EditText"));
        addId("ALLİANZ YAŞAM EMEKLİLİK TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU", By.xpath("(//*[@text='TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU'])//..//android.widget.EditText"));
        addId("ALLİANZ YAŞAM EMEKLİLİK KATKI PAYLARIM", By.id("com.accenture.oneapp.prep:id/input_my_contributions"));
        addId("ALLİANZ YAŞAM EMEKLİLİK BİRİKİMLERİM", By.id("com.accenture.oneapp.prep:id/input_my_savings"));
        addId("ALLİANZ YAŞAM EMEKLİLİK FON DAĞILIMI GÖNDER BUTONU", By.id("com.accenture.oneapp.prep:id/fund_change_button_save"));
        addId("ALLİANZ YAŞAM EMEKLİLİK FON DAĞILIMINI DEĞİŞTİR BUTONU", By.id("com.accenture.oneapp.prep:id/fund_details_change_button"));
        addId("ALLİANZ YAŞAM EMEKLİLİK TOPLAM BİRİKİMİM", By.id("com.accenture.oneapp.prep:id/total_saving"));
        addId("ALLİANZ YAŞAM EMEKLİLİK TOPLAM BİRKİMİM SAYFASI", By.id("com.accenture.oneapp.prep:id/savings_view"));
        addId("ALLİANZ YAŞAM EMEKLİLİK TAHMİNİ BİRİKİMİM", By.id("com.accenture.oneapp.prep:id/estimated_saving"));
        addId("ALLİANZ YAŞAM EMEKLİLİK TAHMİNİ BİRKİMİM SAYFASI", By.id("com.accenture.oneapp.prep:id/main_layout"));
        addId("ALLİANZ YAŞAM EMEKLİLİK EK FAYDALAR", By.id("com.accenture.oneapp.prep:id/extra_benefits"));
        addId("ALLİANZ YAŞAM EMEKLİLİK EK FAYDALAR SAYFASI", By.id("com.accenture.oneapp.prep:id/webview"));
        addId("AZYE İLK POLİÇE/SÖZLEŞMEYE", By.id("com.accenture.oneapp.prep:id/view_container_policy"));
        addId("ALLİANZ YAŞAM EMEKLİLİK POLİÇE/SÖZLEŞMELER SAYFASI", By.id("com.accenture.oneapp.prep:id/contract_details_slider"));
        addId("ALLİANZ YAŞAM EMEKLİLİK KATKI PAYI TUTARI KALEM İKONU", By.id("com.accenture.oneapp.prep:id/details_item_details"));
        addId("ALLİANZ YAŞAM EMEKLİLİK KATKI PAYI TUTARI", By.id("com.accenture.oneapp.prep:id/details_item_text_right"));
        addId("ALLİANZ YAŞAM EMEKLİLİK KATKI PAYI TUTARI GÜNCELLE BUTONU", By.id("com.accenture.oneapp.prep:id/contribution_update_button"));
        addId("ALLİANZ YAŞAM EMEKLİLİK KATKI PAYI TUTARI GÖNDER BUTONU", By.id("com.accenture.oneapp.prep:id/fund_pay_send_info_button"));
        addId("ALLİANZ YAŞAM EMEKLİLİK KATKI PAYI ŞİFRE", By.id("com.accenture.oneapp.prep:id/dialog_sms_code"));
        addId("ALLİANZ YAŞAM EMEKLİLİK KATKI PAYI TUTARI TAMAM BUTONU", By.id("com.accenture.oneapp.prep:id/dialog_sms_send"));
        addId("ALLİANZ YAŞAM EMEKLİLİK KATKI PAYI TUTARI BİLGİ ONAY BUTONU", By.id("com.accenture.oneapp.prep:id/action_primary"));
        addId("ALLİANZ YAŞAM EMEKLİLİK ÖDEME PERİYODU VE GÜNÜ KALEM İKONU", By.xpath("//*[@resource-id='com.accenture.oneapp.prep:id/payment_period']/android.widget.LinearLayout/android.view.ViewGroup/android.widget.FrameLayout/android.widget.ImageView"));
        addId("ALLİANZ YAŞAM EMEKLİLİK ÖDEME PERİYODU VE GÜNÜ ALANI", By.id("com.accenture.oneapp.prep:id/period_day_selection_text"));
        addId("ALLİANZ YAŞAM EMEKLİLİK ÖDEME PERİYODU VE GÜNÜ SÜREÇ", By.xpath("//android.widget.NumberPicker[1]/android.widget.Button[2]"));
        addId("ALLİANZ YAŞAM EMEKLİLİK ÖDEME PERİYODU VE GÜNÜ TAMAM BUTONU", By.id("com.accenture.oneapp.prep:id/dialog_period_day_picker_ok"));
        addId("ALLİANZ YAŞAM EMEKLİLİK ÖDEME PERİYODU VE GÜNÜ GÜNCELLE", By.id("com.accenture.oneapp.prep:id/update_payment_period_save"));
        addId("ALLİANZ YAŞAM EMEKLİLİK ÖDEME PERİYODU VE GÜNÜ GÖNDER BUTONU", By.id("com.accenture.oneapp.prep:id/fund_pay_send_info_button"));
        addId("ALLİANZ YAŞAM EMEKLİLİK ÖDEME PERİYODU VE GÜNÜ ŞİFRE", By.id("com.accenture.oneapp.prep:id/dialog_sms_code"));
        addId("ALLİANZ YAŞAM EMEKLİLİK ÖDEME PERİYODU VE GÜNÜ ŞİFRE TAMAM BUTONU", By.id("com.accenture.oneapp.prep:id/dialog_sms_send"));
        addId("ALLİANZ YAŞAM EMEKLİLİK ÖDEME PERİYODU BİLGİ ONAY BUTONU", By.id("com.accenture.oneapp.prep:id/action_primary"));
        addId("ALLİANZ YAŞAM EMEKLİLİK BİRİKİM DETAYIM TABI", By.id("com.accenture.oneapp.prep:id/contract_details_saving_details"));
        addId("ALLİANZ YAŞAM EMEKLİLİK BİRİKİM DETAYIM SAYFASI", By.id("com.accenture.oneapp.prep:id/saving_details_slider"));
        addId("ALLİANZ YAŞAM EMEKLİLİK ÖDEMELERİM TABI", By.id("com.accenture.oneapp.prep:id/contract_details_payments"));
        addId("ALLİANZ YAŞAM EMEKLİLİK ÖDEMELERİM SAYFASI", By.id("android:id/content"));
        addId("ALLİANZ YAŞAM EMEKLİLİK FONLARIM", By.id("com.accenture.oneapp.prep:id/contract_details_funds"));
        addId("ALLİANZ YAŞAM EMEKLİLİK FONLARIM SAYFASI", By.id("com.accenture.oneapp.prep:id/fund_details_slider"));
        addId("ALLİANZ YAŞAM EMEKLİLİK FON DAĞILIMINI DEĞİŞTİR BUTONU", By.id("com.accenture.oneapp.prep:id/fund_details_change_button"));
        addId("ALLİANZ YAŞAM EMEKLİLİK TOPLAM BİRİKİMİM", By.id("com.accenture.oneapp.prep:id/total_saving"));
        addId("ALLİANZ YAŞAM EMEKLİLİK TOPLAM BİRKİMİM SAYFASI", By.id("com.accenture.oneapp.prep:id/savings_view"));
        addId("ALLİANZ YAŞAM EMEKLİLİK TAHMİNİ BİRİKİMİM", By.id("com.accenture.oneapp.prep:id/estimated_saving"));
        addId("ALLİANZ YAŞAM EMEKLİLİK TAHMİNİ BİRKİMİM SAYFASI", By.id("com.accenture.oneapp.prep:id/main_layout"));
        addId("ALLİANZ YAŞAM EMEKLİLİK EK FAYDALAR", By.id("com.accenture.oneapp.prep:id/extra_benefits"));
        //addId("ALLİANZ YAŞAM EMEKLİLİK EK FAYDALAR SAYFASI", By.xpath("//*[@text='Ek Faydalar']"));
        addId("ALLİANZ YAŞAM EMEKLİLİK EK FAYDALAR SAYFASI", By.id("android:id/content"));
        addId("ALLİANZ EMEKLİLİK DÜNYASI", By.xpath("//android.widget.LinearLayout[6]/android.widget.LinearLayout"));
        addId("ALLİANZ EMEKLİLİK DÜNYASI İNCELE", By.id("com.accenture.oneapp.prep:id/btn_review_package"));
        //addId("ALLİANZ EMEKLİLİK DÜNYASI SAYFASI", By.id("com.accenture.oneapp.prep:id/container_retirement_world_packages"));
        addId("ALLİANZ EMEKLİLİK DÜNYASI SAYFASI", By.id("android:id/content"));
        addId("GECMİS POLİCELERİM", By.id("//android.widget.LinearLayout[3]/android.widget.LinearLayout"));
        addId("GECMİS POLİCELERİM SAYFASINA", By.id("//android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout"));
        addId("AKILLI BİREYSEL EMEKLİLİK SİSTEMİ PROGRAMI", By.xpath("//android.widget.TextView[contains(@text, 'AkıllıBES')]"));
        addId("AKILLI BİREYSEL EMEKLİLİK SİSTEMİ PROGRAMI SAYFASI", By.id("com.accenture.oneapp.prep:id/rv_smart_pension_introduction"));
        addId("AKILLI BİREYSEL EMEKLİLİK SİSTEMİ'NE KATIL BUTONU", By.id("com.accenture.oneapp.prep:id/btn_join_smart_pension"));
        addId("AKILLI BİREYSEL EMEKLİLİK SİSTEMİ PROGRAMI 2.SAYFA", By.id("android:id/content"));
        addId("KİŞİSEL VERİ KORUNUMU KABULÜ", By.id("com.accenture.oneapp.prep:id/checkbox_confirm_kvkk"));
        addId("AKILLI BİREYSEL EMEKLİLİK SİSTEMİ PROGRAMI'NA KATIL BUTONU", By.id("com.accenture.oneapp.prep:id/btn_join_smart_pension_program"));
        addId("DOĞUM YILI ALANI", By.xpath("//android.widget.LinearLayout[2]/android.widget.FrameLayout"));
        addId("DOĞUM YILI SEÇİMİ", By.xpath("//android.widget.ListView/android.widget.TextView[2]"));
        addId("MEDENİ DURUM ALANI", By.xpath("//android.widget.LinearLayout[3]/android.widget.FrameLayout/android.widget.Spinner"));
        addId("MEDENİ DURUM SEÇİMİ", By.xpath("//android.widget.ListView/android.widget.TextView[2]"));
        addId("ÇOCUK SAYISI ALANI", By.xpath("//android.widget.LinearLayout[2]/android.widget.FrameLayout/android.widget.Spinner"));
        addId("ÇOCUK SAYISI SEÇİMİ", By.xpath("//android.widget.ListView/android.widget.TextView[3]"));
        addId("KİRA DURUMUNUZ ALANI", By.xpath("//android.widget.LinearLayout[3]/android.widget.FrameLayout/android.widget.Spinner"));
        addId("KİRA DURUMUNUZ SEÇİMİ", By.xpath("//android.widget.ListView/android.widget.TextView[2]"));
        addId("ÇALIŞMA DURUMUNUZ ALANI", By.xpath("//android.widget.LinearLayout[4]/android.widget.FrameLayout/android.widget.Spinner"));
        addId("ÇALIŞMA DURUMUNUZ SEÇİMİ", By.xpath("//android.widget.ListView/android.widget.TextView[2]"));
        addId("BİREYSEL KREDİ DURUMUNUZ ALANI", By.xpath("//android.widget.LinearLayout[5]/android.widget.FrameLayout/android.widget.Spinner"));
        addId("BİREYSEL KREDİ DURUMUNUZ SEÇİMİ", By.xpath("//android.widget.ListView/android.widget.TextView[2]"));
        addId("AKILLI BİREYSEL EMEKLİLİK SİSTEMİ DEMOGRAFİK SORULAR DEVAM ET", By.id("com.accenture.oneapp.prep:id/btn_item_text"));
        addId("AKILLI BİREYSEL EMEKLİLİK SİSTEMİ PROGRAMI ANKET YANITLARI 1", By.xpath("//android.widget.RadioGroup/android.widget.RadioButton[1]"));
        addId("AKILLI BİREYSEL EMEKLİLİK SİSTEMİ PROGRAMI ANKET YANITLARI 2", By.xpath("//android.widget.RadioGroup/android.widget.RadioButton[1]"));
        addId("AKILLI BİREYSEL EMEKLİLİK SİSTEMİ PROGRAMI ANKET YANITLARI 3", By.xpath("//android.widget.RadioGroup/android.widget.RadioButton[1]"));
        addId("AKILLI BİREYSEL EMEKLİLİK SİSTEMİ PROGRAMI ANKET YANITLARI 4", By.xpath("//android.widget.RadioGroup/android.widget.RadioButton[1]"));
        addId("AKILLI BİREYSEL EMEKLİLİK SİSTEMİ PROGRAMI ANKET YANITLARI 5", By.xpath("//android.widget.RadioGroup/android.widget.RadioButton[1]"));
        addId("AKILLI BİREYSEL EMEKLİLİK SİSTEMİ PROGRAMI ANKET YANITLARI 6", By.xpath("//android.widget.RadioGroup/android.widget.RadioButton[1]"));
        addId("AKILLI BİREYSEL EMEKLİLİK SİSTEMİ PROGRAMI ANKET DEVAM ET BUTONU", By.id("com.accenture.oneapp.prep:id/btn_sp_offer"));
        addId("AKILLI BİREYSEL EMEKLİLİK SİSTEMİ PROGRAMI DEVAM ET", By.id("com.accenture.oneapp.prep:id/btn_item_text"));
        addId("AKILLI BİREYSEL EMEKLİLİK SİSTEMİ PROGRAMI FON DAGILIMINIZ HAZIR SAYFASI", By.id("android:id/content"));
        addId("AKILLI BİREYSEL EMEKLİLİK SİSTEMİ PROGRAMI FON DAĞILIMI DEĞİŞİKLĞİ YAP BUTONU", By.id("com.accenture.oneapp.prep:id/sp_funds_change_button"));
        addId("AKILLI BİREYSEL EMEKLİLİK SİSTEMİ PROGRAMI FON DAĞILIMI DEĞİŞİKLĞİ KABUL EDİYORUM BUTONU", By.id("com.accenture.oneapp.prep:id/action_primary"));
        addId("AKILLI BİREYSEL EMEKLİLİK SİSTEMİ PROGRAMI FON DAĞILIMI DEĞİŞİKLĞİ GÖNDER BUTONU", By.id("com.accenture.oneapp.prep:id/fund_pay_send_info_button"));
        addId("GECMİŞ POLİÇELERİM BİRİKİMLERİM", By.xpath("//*[@text='Geçmiş Poliçelerim']"));
        addId("GECMİŞ POLİÇELERİM BİRİKİMLERİM SAYFASI", By.id("com.accenture.oneapp.prep:id/decor_content_parent"));
        addId("PAKET DEĞİŞİKLİĞİ BU MESAJI BİR DAHA GÖSTERME", By.id("com.accenture.oneapp.prep:id/change_free_dialog_checkBox"));
        addId("PAKET DEĞİŞİKLİĞİ EVET", By.id("com.accenture.oneapp.prep:id/fund_change_dialog_yes_button"));

        addId("ALLIANZ YAŞAM EMEKLİLİK AKILLIBES YENİ FON DAĞILIMINI İNCELE BUTONU", By.id("com.accenture.oneapp.prep:id/btn_show_offers"));
        addId("ALLIANZ YAŞAM EMEKLİLİK AKILLIBES FON DAĞILIMI DEĞİŞİKLİĞİ YAP BUTONU", By.id("com.accenture.oneapp.prep:id/sp_funds_change_button"));
        addId("ALLIANZ YAŞAM EMEKLİLİK AKILLIBES FON DAĞILIMI DEĞİŞİKLİĞİ YAP KABUL EDİYORUM BUTONU", By.id("com.accenture.oneapp.prep:id/action_primary"));
        addId("ALLIANZ YAŞAM EMEKLİLİK AKILLIBES FON DAĞILIMI DEĞİŞİKLİĞİ YAP ŞİFRE GÖNDER BUTONU", By.id("com.accenture.oneapp.prep:id/fund_pay_send_info_button"));
        addId("ALLIANZ YAŞAM EMEKLİLİK AKILLIBES FON DAĞILIMI DEĞİŞİKLİĞİ YAP ŞİFRE ALANI", By.id("com.accenture.oneapp.prep:id/fund_phone_password_editText"));
        addId("ALLIANZ YAŞAM EMEKLİLİK AKILLIBES FON DAĞILIMI DEĞİŞİKLİĞİ YAP ŞİFRE GÖNDERİMİ BUTONU", By.id("com.accenture.oneapp.prep:id/fund_phone_password_send_button"));
        addId("ALLIANZ YAŞAM EMEKLİLİK AKILLIBES FON DAĞILIMI DEĞİŞİKLİĞİ İŞLEMİ SONUCU", By.id("com.accenture.oneapp.prep:id/txt_result"));
        addId("ALLIANZ YAŞAM EMEKLİLİK AKILLIBES FON DAĞILIMI DEĞİŞİKLİĞİ İŞLEM BİLGİLENDİRME ALANI", By.id("com.accenture.oneapp.prep:id/txt_action_message"));
        addId("ALLIANZ YAŞAM EMEKLİLİK AKILLIBES FON DAĞILIMINI UYGULAMAK İSTEMİYORUM BUTONU", By.id("com.accenture.oneapp.prep:id/sp_funds_reject_advice_button"));
        addId("ALLIANZ YAŞAM EMEKLİLİK AKILLIBES PROGRAMINDAN AYRIL BUTONU", By.id("com.accenture.oneapp.prep:id/txt_leave_sp"));
        addId("ALLIANZ YAŞAM EMEKLİLİK AKILLIBES FON DAĞILIMI DEĞİŞİKLİĞİ İŞLEMİ SONUCU KAPAMA BUTONU", By.id("com.accenture.oneapp.prep:id/action_close"));
        addId("ALLIANZ YAŞAM EMEKLİLİK AKILLIBES DEMOGRAFİK BİLGİLERİMİ GÜNCELLE BUTONU", By.id("com.accenture.oneapp.prep:id/btn_update_demographic_questions"));
        addId("ALLIANZ YAŞAM EMEKLİLİK FONLARIM AKILLI BES ÜYESİ OLMAK İSTER MİSİN BUTONU", By.id("com.accenture.oneapp.prep:id/img_smart_pension_detail"));
        addId("ALLIANZ YAŞAM EMEKLİLİK FONLARIM AKILLI BES DEMOGRAFİK BİLGİ GÜNCELLEME ALANI", By.id("com.accenture.oneapp.prep:id/txt_smart_pension"));
        addId("ALLİANZ YAŞAM EMEKLİLİK FONLARIM AKILLI BES UYARISI EVET BUTONU", By.id("com.accenture.oneapp.prep:id/action_primary"));
        addId("ALLIANZ YAŞAM EMEKLİLİK FONLARIM AKILLI BES YENİ FON DAĞILIMI BİLDİRİMİ", By.id("com.accenture.oneapp.prep:id/img_smart_pension_detail"));
        addId("ALLIANZ YASAM EMEKLİLİK FON DAĞILIMI DEĞİŞİKLİĞİ TALEBİ BİLGİ ALANI", By.id("com.accenture.oneapp.prep:id/dialog_content"));

        //AZHE
        addId("ALLİANZ HAYAT EMEKLİLİK İLK POLİÇE/SÖZLEŞMEYE", By.id("com.accenture.oneapp.prep:id/view_container_policy"));
        addId("ALLİANZ HAYAT EMEKLİLİK POLİÇE/SÖZLEŞMELER SAYFASI", By.id("com.accenture.oneapp.prep:id/contract_details_slider"));
        addId("ALLİANZ HAYAT EMEKLİLİK KATKI PAYI TUTARI KALEM İKONU", By.id("com.accenture.oneapp.prep:id/details_item_details"));
        addId("ALLİANZ HAYAT EMEKLİLİK KATKI PAYI TUTARI", By.id("com.accenture.oneapp.prep:id/details_item_text_right"));
        addId("ALLİANZ HAYAT EMEKLİLİK KATKI PAYI TUTARI GÜNCELLE BUTONU", By.id("com.accenture.oneapp.prep:id/contribution_update_button"));
        addId("ALLİANZ HAYAT EMEKLİLİK KATKI PAYI TUTARI GÖNDER BUTONU", By.id("com.accenture.oneapp.prep:id/fund_pay_send_info_button"));
        addId("ALLİANZ HAYAT EMEKLİLİK KATKI PAYI ŞİFRE", By.id("com.accenture.oneapp.prep:id/dialog_sms_code"));
        addId("ALLİANZ HAYAT EMEKLİLİK KATKI PAYI TUTARI TAMAM BUTONU", By.id("com.accenture.oneapp.prep:id/dialog_sms_send"));
        addId("ALLİANZ HAYAT EMEKLİLİK ÖDEME PERİYODU VE GÜNÜ KALEM İKONU", By.xpath("//android.widget.FrameLayout/android.widget.ImageView"));
        addId("ALLİANZ HAYAT EMEKLİLİK ÖDEME PERİYODU VE GÜNÜ ALANI", By.id("com.accenture.oneapp.prep:id/period_day_selection_text"));
        addId("ALLİANZ HAYAT EMEKLİLİK ÖDEME PERİYODU VE GÜNÜ SÜREÇ", By.xpath("android.widget.NumberPicker[1]/android.widget.Button[2]"));
        addId("ALLİANZ HAYAT EMEKLİLİK ÖDEME PERİYODU VE GÜNÜ TAMAM BUTONU", By.id("com.accenture.oneapp.prep:id/dialog_period_day_picker_ok"));
        addId("ALLİANZ HAYAT EMEKLİLİK ÖDEME PERİYODU VE GÜNÜ GÜNCELLE", By.id("com.accenture.oneapp.prep:id/update_payment_period_save"));
        addId("ALLİANZ HAYAT EMEKLİLİK ÖDEME PERİYODU VE GÜNÜ GÖNDER BUTONU", By.id("com.accenture.oneapp.prep:id/fund_pay_send_info_button"));
        addId("ALLİANZ HAYAT EMEKLİLİK ÖDEME PERİYODU VE GÜNÜ ŞİFRE", By.id("com.accenture.oneapp.prep:id/dialog_sms_code"));
        addId("ALLİANZ HAYAT EMEKLİLİK ÖDEME PERİYODU VE GÜNÜ TAMAM BUTONU", By.id("com.accenture.oneapp.prep:id/dialog_sms_send"));
        addId("ALLİANZ HAYAT EMEKLİLİK BİRİKİM DETAYIM TABI", By.id("com.accenture.oneapp.prep:id/contract_details_saving_details"));
        addId("ALLİANZ HAYAT EMEKLİLİK BİRİKİM DETAYIM SAYFASI", By.id("com.accenture.oneapp.prep:id/saving_details_slider"));
        addId("ALLİANZ HAYAT EMEKLİLİK ÖDEMELERİM TABI", By.id("com.accenture.oneapp.prep:id/contract_details_payments"));
        addId("ALLİANZ HAYAT EMEKLİLİK ÖDEMELERİM SAYFASI", By.id("android:id/content"));
        addId("ALLİANZ HAYAT EMEKLİLİK FONLARIM", By.id("com.accenture.oneapp.prep:id/contract_details_funds"));
        addId("ALLİANZ HAYAT EMEKLİLİK FONLARIM SAYFASI", By.id("com.accenture.oneapp.prep:id/fund_details_slider"));
        addId("ALLİANZ HAYAT EMEKLİLİK FON DAĞILIMINI DEĞİŞTİR BUTONU", By.id("com.accenture.oneapp.prep:id/fund_details_change_button"));
        addId("ALLİANZ HAYAT EMEKLİLİK FONLARIM AKILLI BES UYARISI EVET BUTONU", By.id("com.accenture.oneapp.prep:id/action_primary"));
        addId("ALLİANZ HAYAT EMEKLİLİK TOPLAM BİRİKİMİM", By.id("com.accenture.oneapp.prep:id/total_saving"));
        addId("ALLİANZ HAYAT EMEKLİLİK TOPLAM BİRKİMİM SAYFASI", By.id("com.accenture.oneapp.prep:id/savings_view"));
        addId("ALLİANZ HAYAT EMEKLİLİK TOPLAM BİRKİMİM İLK POLİÇE", By.xpath("//android.widget.FrameLayout[2]/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.ListView/android.view.ViewGroup"));

        addId("ALLİANZ HAYAT EMEKLİLİK TAHMİNİ BİRİKİMİM", By.id("com.accenture.oneapp.prep:id/estimated_saving"));
        addId("ALLİANZ HAYAT EMEKLİLİK TAHMİNİ BİRİKİMİM SAYFASI", By.id("com.accenture.oneapp.prep:id/estimate_calculation_scroll_view"));
        addId("ALLİANZ HAYAT EMEKLİLİK EK FAYDALAR", By.id("com.accenture.oneapp.prep:id/extra_benefits"));
        addId("ALLİANZ HAYAT EMEKLİLİK EK FAYDALAR SAYFASI", By.id("android:id/content"));

        //MYALLIANZ LOGİNLİ - POLİÇE KARTLARIM
        addId("POLİÇE KARTLARI ALANI", By.id("com.accenture.oneapp.prep:id/layout_my_products"));
        addId("POLİÇE DETAYI SAYFASI BAŞLIĞI" ,By.id("com.accenture.oneapp.prep:id/action_bar_title"));
        addId("TÜMÜNÜ GÖR BUTONU", By.id("com.accenture.oneapp.prep:id/txt_show_all_products"));

        //MYALLIANZ LOGİNLİ - POLİÇE KARTLARIM - HIZLI İŞLEMLER
        addId("HIZLI İŞLEMLER ALANI İLK SEÇENEK", By.xpath("(//*[@resource-id='com.accenture.oneapp.prep:id/ll_quick_transactions_container'])/android.view.ViewGroup[1]"));
        addId("HIZLI İŞLEMLER VAZGEÇ BUTONU", By.id("com.accenture.oneapp.prep:id/btn_quick_transactions_ok"));
        addId("HIZLI İŞLEMLER FON DAĞILIM DEĞİŞİKLİĞİ YAP BUTONU", By.xpath("//android.widget.TextView[@text='Fon Dağılım Değişikliği Yap']"));
        addId("HIZLI İŞLEMLER AKILLIBES'İ İNCELE BUTONU", By.xpath("//android.widget.TextView[@text=\"AkıllıBES'i İncele\"]"));
        addId("HIZLI İŞLEMLER SÖZLEŞME DETAYLARINI GÖSTER BUTONU", By.xpath("//android.widget.TextView[@text=\"Sözleşme Detaylarını Göster\"]"));
        addId("FONLARIM SAYFASI İÇERİĞİ", By.id("com.accenture.oneapp.prep:id/fund_details_slider"));
        addId("AKILLIBES PROGRAMI SAYFASI İÇERİĞİ", By.id("com.accenture.oneapp.prep:id/rv_smart_pension_introduction"));
        addId("SÖZLEŞME DETAYLARI SAYFASI İÇERİĞİ", By.id("com.accenture.oneapp.prep:id/contract_details_slider"));
        addId("HIZLI İŞLEMLER ÖDEMELERİMİ GÖSTER BUTONU", By.xpath("//android.widget.TextView[@text='Ödemelerimi Göster']"));
        addId("HIZLI İŞLEMLER HASARIM VAR BUTONU", By.xpath("//android.widget.TextView[@text='Hasarım Var']"));
        addId("HIZLI İŞLEMLER POLİÇE İŞLEMLERİ BUTONU", By.xpath("//android.widget.TextView[@text='Poliçe İşlemleri']"));
        addId("HIZLI İŞLEMLER POLİÇE DETAYLARINI GÖSTER", By.xpath("//android.widget.TextView[@text='Poliçe Detaylarını Göster']"));
        addId("SAYFA BAŞLIĞI",By.id("com.accenture.oneapp.prep:id/action_bar_title"));
        addId("ÖDEME PLANI VE DETAYLARI SAYFASI İÇERİĞİ", By.id("com.accenture.oneapp.prep:id/unpaid_installment_recyclerview"));
        addId("HIZLI İŞLEMLER SAĞLIK HARCAMA TALEBİ OLUŞTUR BUTONU", By.xpath("//android.widget.TextView[@text='Sağlık Harcama Talebi Oluştur']"));
        addId("HIZLI İŞLEMLER POLİÇE DETAYLARINI GÖSTER BUTONU", By.xpath("//android.widget.TextView[@text='Poliçe Detaylarını Göster']"));
        addId("SAĞLIK HARCAMASI TALEBİ SAYFASI İÇERİĞİ" , By.id("com.accenture.oneapp.prep:id/create_refund_info_layout"));
        addId("POLİÇEM SAYFASI İÇERİĞİ", By.id("com.accenture.oneapp.prep:id/root_policy_detail"));
        addId("GÜNCEL POLİÇELER LİSTESİ İLK POLİÇE", By.xpath("//androidx.recyclerview.widget.RecyclerView/android.view.ViewGroup[1]"));
        addId("GEÇMİŞ POLİÇELER TABI", By.id("com.accenture.oneapp.prep:id/tabs_button_right"));
        addId("GEÇMİŞ POLİÇELER LİSTESİ İLK POLİÇE", By.xpath("//androidx.recyclerview.widget.RecyclerView/android.view.ViewGroup[1]"));

        //MYALLIANZ LOGİNLİ - SİZE NASIL YARDIMCI OLABİLİRİZ ALANI
        addId("ANLAŞMALI SAĞLIK KURUMU BUL HARİTA", By.xpath("//android.view.View[@content-desc='Google haritası']"));
        addId("ARAÇ SERVİSİ BUL", By.xpath("//android.widget.FrameLayout/android.view.ViewGroup/android.widget.LinearLayout/android.view.ViewGroup[2]"));
        addId("ANLAŞMALI SERVİS BUL SAYFASI İÇERİĞİ", By.id("com.accenture.oneapp.prep:id/my_map_car_search_container"));
        addId("ÖDEMELERİ GÖSTER BUTONU", By.id("com.accenture.oneapp.prep:id/board_item_belated_payment"));

        //MYALLIANZ LOGİNLİ - KAMPANYALAR - STORY ALANI
        addId("KAMPANYALAR İLK KAMPANYA BUTONU", By.xpath("//androidx.recyclerview.widget.RecyclerView/android.view.ViewGroup[1]"));
        addId("HEMEN İNCELE BUTONU", By.id("com.accenture.oneapp.prep:id/btnStoryItem"));
        addId("KAMPANYA STORY İÇERİĞİ", By.id("com.accenture.oneapp.prep:id/storyOverlay"));
        addId("KAMPANYA KOŞULLARI DROPDOWN BUTONU", By.id("com.accenture.oneapp.prep:id/ll_show_conditions"));
        addId("KAMPANYA KOŞULLARI İÇERİĞİ", By.id("com.accenture.oneapp.prep:id/txt_term_of_conditions"));
        addId("KAMPANYA KODU AL BUTONU", By.id("com.accenture.oneapp.prep:id/btn_participate_campaign"));
        addId("KAMPANYA KODU ALANI", By.id("com.accenture.oneapp.prep:id/stateful_view_campaign_status"));
        addId("TÜM KAMPANYALAR LİSTESİ ALANI", By.id("com.accenture.oneapp.prep:id/rv_campaign_summary"));
        addId("TÜM KAMPANYALAR LİSTESİ İLK KAMPANYA", By.xpath("//androidx.recyclerview.widget.RecyclerView/android.view.ViewGroup[1]"));
        addId("KATILDIKLARIM TABI", By.xpath("//androidx.appcompat.app.ActionBar.Tab[@content-desc='Katıldıklarım']"));
        addId("KATILINAN KAMPANYA LİSTESİ", By.id("com.accenture.oneapp.prep:id/rv_campaign_participants"));
        addId("KATILINAN KAMPANYA LİSTESİ İLK KAMPANYA KOPYALAMA BUTONU", By.xpath("//androidx.recyclerview.widget.RecyclerView/android.view.ViewGroup[1]/android.widget.ImageView"));
        addId("KATILINAN KAMPANYA LİSTESİ İLK KAMPANYA KOD ALANI", By.xpath("//*[@resource-id='com.accenture.oneapp.prep:id/txt_campaign_code']"));
        addId("KATILINAN KAMPANYA LİSTESİ İLK KAMPANYA KAMPANYA DETAYLARI BUTONU", By.xpath("//*[@resource-id='com.accenture.oneapp.prep:id/txt_see_campaign']"));

        //DİĞER TABI
        addId("DİĞER TABI İLK POLİÇE", By.xpath("//androidx.recyclerview.widget.RecyclerView/android.view.ViewGroup[1]"));



        //SİZE NASIL YARDIMCI OLABİLİRİZ - HIZLI TEKLİF AL - UATLER PREP OLACAK
        addId("HIZLI TEKLİF AL BUTONU" , By.id("com.accenture.oneapp.prep:id/board_item_get_offer_from_lead_form"));
        addId("HIZLI TEKLİF AL SAYFA İÇERİĞİ", By.id("com.accenture.oneapp.prep:id/stateful_view_lead_form_categories"));
        addId("HIZLI TEKLİF AL KATEGORİ ALANI", By.id("com.accenture.oneapp.prep:id/rv_lead_categories"));
        addId("HIZLI TEKLİF AL KATEGORİ ALANI İLK KATEGORİ", By.xpath("//androidx.recyclerview.widget.RecyclerView/android.view.ViewGroup[1]"));
        addId("HIZLI TEKLİF AL SANDVİÇ MENÜ LİSTESİ", By.id("com.accenture.oneapp.prep:id/rv_lead_product_detail"));
        addId("HIZLI TEKLİF AL SANDVİÇ MENÜ İLK ÜRÜN OK BUTONU", By.xpath("//androidx.recyclerview.widget.RecyclerView/android.view.ViewGroup[1]/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.RadioGroup/android.widget.ImageView"));
        addId("HIZLI TEKLİF AL SANDVİÇ MENÜ ÜRÜN DETAY ALANI", By.id("com.accenture.oneapp.prep:id/txt_expanded_description"));
        addId("SİZİ ARAYALIM BUTONU", By.id("com.accenture.oneapp.prep:id/btn_lead_product_call_me"));
        addId("HIZLI TEKLİF AL SANDVİÇ MENÜ İLK ÜRÜN RADYO BUTONU", By.xpath("//androidx.recyclerview.widget.RecyclerView/android.view.ViewGroup[1]/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.RadioGroup/android.widget.RadioButton"));
        addId("HIZLI TEKLİF AL FORMU", By.id("com.accenture.oneapp.prep:id/stateful_view_lead_form_offer"));
        addId("HIZLI TEKLİF AL FORMU TCKN ALANI", By.xpath("//android.widget.LinearLayout[@resource-id='com.accenture.oneapp.prep:id/input_identity']/android.widget.LinearLayout/android.widget.EditText"));
        addId("HIZLI TEKLİF AL FORMU DOĞUM TARİHİ ALANI", By.id("com.accenture.oneapp.prep:id/input_birthday"));
        addId("HIZLI TEKLİF AL FORMU CEP TELEFONU ALANI", By.xpath("//android.widget.LinearLayout[@resource-id='com.accenture.oneapp.prep:id/input_phone_number']/android.widget.LinearLayout/android.widget.EditText"));
        addId("HIZLI TEKLİF AL FORMU EMAİL ALANI", By.xpath("//android.widget.LinearLayout[@resource-id='com.accenture.oneapp.prep:id/input_mail_address']/android.widget.LinearLayout/android.widget.EditText"));
        addId("HIZLI TEKLİF AL FORMU SİZİ ARAYALIM BUTONU", By.id("com.accenture.oneapp.prep:id/call_you_button"));
        addId("HIZLI TEKLİF AL FORMU KİŞİSEL VERİ İŞLEME CHECKBOXU", By.xpath("//android.widget.CheckBox[@content-desc='isKvkkPermit']"));
        addId("HIZLI TEKLİF AL FORMU TİCARİ ELEKTRONİK İLETİ CHECKBOXU", By.xpath("//android.widget.CheckBox[@content-desc='isMdmPermit']"));
        addId("HIZLI TEKLİF AL ÖZEL SAĞLIK SİGORTALARI", By.xpath("//androidx.recyclerview.widget.RecyclerView/android.view.ViewGroup[2]")); //ileride silinebilir deneme amaçlı eklendi
        addId("HIZLI TEKLİF AL VAROLAN POLİÇE İÇİN HIZLI TEKLİF UYARI MESAJI ALANI", By.xpath("//*[@resource-id='com.accenture.oneapp.prep:id/ll_generic_transactions_container']"));
        addId("HIZLI TEKLİF AL VAROLAN POLİÇE İÇİN HIZLI TEKLİF UYARI MESAJI İÇERİĞİ", By.xpath("//*[@resource-id='com.accenture.oneapp.prep:id/ll_generic_transactions_container']/android.widget.TextView[2]"));
        addId("HIZLI TEKLİF AL DUPLİKE TEKLİF İÇİN HIZLI TEKLİF UYARI MESAJI ALANI", By.xpath("//*[@resource-id='com.accenture.oneapp.prep:id/ll_generic_transactions_container']"));
        addId("HIZLI TEKLİF AL DUPLİKE TEKLİF İÇİN HIZLI TEKLİF UYARI MESAJI İÇERİĞİ", By.xpath("//*[@resource-id='com.accenture.oneapp.prep:id/ll_generic_transactions_container']/android.widget.TextView[2]"));
        addId("HIZLI TEKLİF AL TEKLİF TALEBİ ALINMIŞTIR YAZISI", By.id("com.accenture.oneapp.prep:id/text_header"));
        addId("HIZLI TEKLİF AL TEKLİF TALEBİ ALINMIŞTIR GÖRSELİ", By.id("com.accenture.oneapp.prep:id/icon_success"));


        //UAT İÇİN ID TANIMLARI
        /*addId("KARŞILAMA EKRANI GİRİŞ YAP", By.id("com.accenture.oneapp.uat:id/btn_view_main_board_not_login"));
        addId("TC KİMLİK NUMARASI", By.id("com.accenture.oneapp.uat:id/input_edittext"));
        addId("ŞİFRENİZ", By.xpath("//*[@resource-id='com.accenture.oneapp.uat:id/input_password']//android.widget.EditText"));
        addId("GİRİŞ YAP", By.id("com.accenture.oneapp.uat:id/action_signin"));
        addId("UYGULAMAMIZA HOŞ GELDİNİZ DEVAM ET", By.id("com.accenture.oneapp.uat:id/button_continue"));*/


    }
}
